-- Your SQL goes here
CREATE TABLE Chats(
    Id UUID PRIMARY KEY ,
    Message VARCHAR(255) NOT NULL,
    ToId UUID NOT NULL REFERENCES Users(Id) ON DELETE CASCADE ,
    FromId UUID NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);