-- Your SQL goes here
CREATE TABLE Posts(
    Id UUID PRIMARY KEY ,
    Description VARCHAR(255) NOT NULL,
    Views BIGINT NOT NULL DEFAULT (0),
    UserId UUID NOT NULL REFERENCES Users(Id) ON DELETE CASCADE ,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);